"""Initial migration with auth

Revision ID: 9985debc9dbe
Revises: 
Create Date: 2025-11-27 09:48:27.718407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9985debc9dbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('customers', 'zip_code',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_index('ix_customers_username', table_name='customers')
    op.create_unique_constraint(None, 'customers', ['email'])
    op.create_unique_constraint(None, 'customers', ['username'])
    op.alter_column('staffs', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('staffs', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('staffs', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('staffs', 'phone',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('staffs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('idx_staffs_username', table_name='staffs')
    op.drop_constraint('staffs_email_key', 'staffs', type_='unique')
    op.create_index(op.f('ix_staffs_email'), 'staffs', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staffs_email'), table_name='staffs')
    op.create_unique_constraint('staffs_email_key', 'staffs', ['email'])
    op.create_index('idx_staffs_username', 'staffs', ['username'], unique=False)
    op.alter_column('staffs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('staffs', 'phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    op.alter_column('staffs', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('staffs', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('staffs', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.create_index('ix_customers_username', 'customers', ['username'], unique=True)
    op.alter_column('customers', 'zip_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
